package com.pencelab.currencyconverter.http.currencylayer;

import com.pencelab.currencyconverter.http.currencylayer.model.Quotes;

import java.util.ArrayList;
import java.util.List;

public class CurrencyLayerCurrencyValueFactory {

    public static List<CurrencyLayerCurrencyValue> getListFromQuotes(Quotes quotes){
        List<CurrencyLayerCurrencyValue> currenciesValues = new ArrayList<>();

        currenciesValues.add(new CurrencyLayerCurrencyValue("AED", quotes.getUSDAED()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("AFN", quotes.getUSDAFN()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("ALL", quotes.getUSDALL()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("AMD", quotes.getUSDAMD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("ANG", quotes.getUSDANG()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("AOA", quotes.getUSDAOA()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("ARS", quotes.getUSDARS()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("AUD", quotes.getUSDAUD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("AWG", quotes.getUSDAWG()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("AZN", quotes.getUSDAZN()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BAM", quotes.getUSDBAM()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BBD", quotes.getUSDBBD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BDT", quotes.getUSDBDT()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BGN", quotes.getUSDBGN()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BHD", quotes.getUSDBHD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BIF", quotes.getUSDBIF()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BMD", quotes.getUSDBMD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BND", quotes.getUSDBND()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BOB", quotes.getUSDBOB()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BRL", quotes.getUSDBRL()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BSD", quotes.getUSDBSD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BTC", quotes.getUSDBTC()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BTN", quotes.getUSDBTN()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BWP", quotes.getUSDBWP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BYN", quotes.getUSDBYN()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BYR", quotes.getUSDBYR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("BZD", quotes.getUSDBZD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("CAD", quotes.getUSDCAD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("CDF", quotes.getUSDCDF()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("CHF", quotes.getUSDCHF()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("CLF", quotes.getUSDCLF()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("CLP", quotes.getUSDCLP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("CNY", quotes.getUSDCNY()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("COP", quotes.getUSDCOP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("CRC", quotes.getUSDCRC()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("CUC", quotes.getUSDCUC()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("CUP", quotes.getUSDCUP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("CVE", quotes.getUSDCVE()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("CZK", quotes.getUSDCZK()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("DJF", quotes.getUSDDJF()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("DKK", quotes.getUSDDKK()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("DOP", quotes.getUSDDOP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("DZD", quotes.getUSDDZD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("EGP", quotes.getUSDEGP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("ERN", quotes.getUSDERN()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("ETB", quotes.getUSDETB()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("EUR", quotes.getUSDEUR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("FJD", quotes.getUSDFJD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("FKP", quotes.getUSDFKP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("GBP", quotes.getUSDGBP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("GEL", quotes.getUSDGEL()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("GGP", quotes.getUSDGGP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("GHS", quotes.getUSDGHS()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("GIP", quotes.getUSDGIP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("GMD", quotes.getUSDGMD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("GNF", quotes.getUSDGNF()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("GTQ", quotes.getUSDGTQ()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("GYD", quotes.getUSDGYD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("HKD", quotes.getUSDHKD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("HNL", quotes.getUSDHNL()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("HRK", quotes.getUSDHRK()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("HTG", quotes.getUSDHTG()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("HUF", quotes.getUSDHUF()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("IDR", quotes.getUSDIDR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("ILS", quotes.getUSDILS()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("IMP", quotes.getUSDIMP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("INR", quotes.getUSDINR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("IQD", quotes.getUSDIQD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("IRR", quotes.getUSDIRR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("ISK", quotes.getUSDISK()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("JEP", quotes.getUSDJEP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("JMD", quotes.getUSDJMD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("JOD", quotes.getUSDJOD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("JPY", quotes.getUSDJPY()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("KES", quotes.getUSDKES()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("KGS", quotes.getUSDKGS()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("KHR", quotes.getUSDKHR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("KMF", quotes.getUSDKMF()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("KPW", quotes.getUSDKPW()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("KRW", quotes.getUSDKRW()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("KWD", quotes.getUSDKWD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("KYD", quotes.getUSDKYD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("KZT", quotes.getUSDKZT()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("LAK", quotes.getUSDLAK()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("LBP", quotes.getUSDLBP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("LKR", quotes.getUSDLKR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("LRD", quotes.getUSDLRD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("LSL", quotes.getUSDLSL()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("LTL", quotes.getUSDLTL()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("LVL", quotes.getUSDLVL()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("LYD", quotes.getUSDLYD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("MAD", quotes.getUSDMAD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("MDL", quotes.getUSDMDL()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("MGA", quotes.getUSDMGA()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("MKD", quotes.getUSDMKD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("MMK", quotes.getUSDMMK()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("MNT", quotes.getUSDMNT()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("MOP", quotes.getUSDMOP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("MRO", quotes.getUSDMRO()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("MUR", quotes.getUSDMUR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("MVR", quotes.getUSDMVR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("MWK", quotes.getUSDMWK()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("MXN", quotes.getUSDMXN()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("MYR", quotes.getUSDMYR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("MZN", quotes.getUSDMZN()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("NAD", quotes.getUSDNAD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("NGN", quotes.getUSDNGN()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("NIO", quotes.getUSDNIO()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("NOK", quotes.getUSDNOK()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("NPR", quotes.getUSDNPR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("NZD", quotes.getUSDNZD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("OMR", quotes.getUSDOMR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("PAB", quotes.getUSDPAB()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("PEN", quotes.getUSDPEN()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("PGK", quotes.getUSDPGK()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("PHP", quotes.getUSDPHP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("PKR", quotes.getUSDPKR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("PLN", quotes.getUSDPLN()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("PYG", quotes.getUSDPYG()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("QAR", quotes.getUSDQAR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("RON", quotes.getUSDRON()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("RSD", quotes.getUSDRSD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("RUB", quotes.getUSDRUB()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("RWF", quotes.getUSDRWF()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("SAR", quotes.getUSDSAR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("SBD", quotes.getUSDSBD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("SCR", quotes.getUSDSCR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("SDG", quotes.getUSDSDG()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("SEK", quotes.getUSDSEK()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("SGD", quotes.getUSDSGD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("SHP", quotes.getUSDSHP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("SLL", quotes.getUSDSLL()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("SOS", quotes.getUSDSOS()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("SRD", quotes.getUSDSRD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("STD", quotes.getUSDSTD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("SVC", quotes.getUSDSVC()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("SYP", quotes.getUSDSYP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("SZL", quotes.getUSDSZL()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("THB", quotes.getUSDTHB()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("TJS", quotes.getUSDTJS()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("TMT", quotes.getUSDTMT()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("TND", quotes.getUSDTND()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("TOP", quotes.getUSDTOP()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("TRY", quotes.getUSDTRY()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("TTD", quotes.getUSDTTD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("TWD", quotes.getUSDTWD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("TZS", quotes.getUSDTZS()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("UAH", quotes.getUSDUAH()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("UGX", quotes.getUSDUGX()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("USD", quotes.getUSDUSD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("UYU", quotes.getUSDUYU()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("UZS", quotes.getUSDUZS()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("VEF", quotes.getUSDVEF()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("VND", quotes.getUSDVND()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("VUV", quotes.getUSDVUV()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("WST", quotes.getUSDWST()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("XAF", quotes.getUSDXAF()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("XAG", quotes.getUSDXAG()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("XAU", quotes.getUSDXAU()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("XCD", quotes.getUSDXCD()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("XDR", quotes.getUSDXDR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("XOF", quotes.getUSDXOF()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("XPF", quotes.getUSDXPF()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("YER", quotes.getUSDYER()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("ZAR", quotes.getUSDZAR()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("ZMK", quotes.getUSDZMK()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("ZMW", quotes.getUSDZMW()));
        currenciesValues.add(new CurrencyLayerCurrencyValue("ZWL", quotes.getUSDZWL()));

        return currenciesValues;
    }



}
